"""AP20 -- retention channel-composition forces the missing self-interaction unit.

TARGET
------
Paper IV measured the plain Hodge/1-form geometry ladder kappa_geo={0,1,1}:
the spin-1/vector sector receives one curvature unit from geometry, while the
Nielsen-Hughes (2s) target needs two. This file tests whether the missing unit
follows from the retention grammar's own ORDERED CHANNEL COMPOSITION, without
taking the Yang-Mills trilinear vertex [a,a] as an input.

PREMISES (declared; this is a conditional derivation, not RD4-alone)
-------------------------------------------------------------------
A1. Channels compose by one UNITAL bilinear associative product m(x,y); the
    identity is the no-op channel and fixes the product normalization.
A2. Directional circulation/curvature is the order defect
        K(x,y) = m(x,y) - m(y,x)
    (the exchange-odd readout of ordered composition).
A3. Self-carrier closure: a channel fluctuation lives in the SAME algebra as
    the background channel, rather than being an external payload.
A4. The quadratic load is the product-induced norm 1/2 ||K||^2.

Then bilinearity alone forces
  K(Ax+e ax, Ay+e ay)
   = K(Ax,Ay) + e(K(Ax,ay)+K(ax,Ay)) + e^2 K(ax,ay),
so the self-interaction term K(ax,ay) occurs with coefficient EXACTLY ONE.
No coefficient is available to fit. In the finite so(3) representation built
from ordinary matrix composition, the Hessian of <K0,K(ax,ay)> supplies one
curvature unit. Combined with Paper IV's independently measured geometric
unit: 1_geo + 1_comp = 2, and the quadratic response is 2^2=4.

HONEST SCOPE
------------
- finite-dimensional algebra/operator diagnostic; no continuum or infinity;
- ordinary unital matrix composition is borrowed mathematics; the candidate-new
  content is the retention reading and the conditional forcing chain A1-A4;
- this does NOT prove that RD4 uniquely forces A1-A4, a gauge group, ghosts,
  the full +11/3 beta coefficient, or the Standard Model;
- the commutative and external-payload controls kill the extra unit.

Run: pytest -q ap/ap20_retention_self_interaction.py
PRIVATE / PROPRIETARY (LICENSE EXCEPTIONS) -- do not publish.
"""
from __future__ import annotations

import numpy as np

TOL = 1e-11


def compose(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Ordered channel composition; no bracket or self-vertex is supplied."""
    return np.asarray(x) @ np.asarray(y)


def order_defect(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Exchange-odd path difference generated from the one product."""
    return compose(x, y) - compose(y, x)


def ad(v: np.ndarray) -> np.ndarray:
    """Finite real 3D representation of an oriented channel generator."""
    x, y, z = np.asarray(v, dtype=float)
    return np.array(
        [[0.0, -z, y], [z, 0.0, -x], [-y, x, 0.0]], dtype=float
    )


def unad(m: np.ndarray) -> np.ndarray:
    """Inverse of ad on its skew-symmetric image."""
    m = np.asarray(m, dtype=float)
    return np.array([m[2, 1], m[0, 2], m[1, 0]], dtype=float)


def channel_bracket(u: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Bracket generated from ordinary composition, not inserted separately."""
    return unad(order_defect(ad(u), ad(v)))


def curvature_coefficients(
    bg_x: np.ndarray,
    bg_y: np.ndarray,
    a_x: np.ndarray,
    a_y: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Coefficients of K(Ax+e ax, Ay+e ay), generated by one bracket."""
    k0 = channel_bracket(bg_x, bg_y)
    k1 = channel_bracket(bg_x, a_y) + channel_bracket(a_x, bg_y)
    k2 = channel_bracket(a_x, a_y)
    return k0, k1, k2


def full_curvature(
    eps: float,
    bg_x: np.ndarray,
    bg_y: np.ndarray,
    a_x: np.ndarray,
    a_y: np.ndarray,
) -> np.ndarray:
    return channel_bracket(bg_x + eps * a_x, bg_y + eps * a_y)


def hessian_from_quadratic(q, dimension: int) -> np.ndarray:
    """Recover H from q(z)=1/2 z^T H z by polarization."""
    eye = np.eye(dimension)
    h = np.zeros((dimension, dimension), dtype=float)
    base = [q(eye[i]) for i in range(dimension)]
    for i in range(dimension):
        h[i, i] = 2.0 * base[i]
        for j in range(i + 1, dimension):
            hij = q(eye[i] + eye[j]) - base[i] - base[j]
            h[i, j] = h[j, i] = hij
    return h


def self_interaction_hessian(bg_x: np.ndarray, bg_y: np.ndarray) -> np.ndarray:
    """Hessian of the forced cross term <K0,K(ax,ay)> only."""
    k0 = channel_bracket(bg_x, bg_y)

    def q_self(z: np.ndarray) -> float:
        a_x, a_y = z[:3], z[3:]
        return float(k0 @ channel_bracket(a_x, a_y))

    return hessian_from_quadratic(q_self, 6)


def curvature_operator(bg_x: np.ndarray, bg_y: np.ndarray) -> np.ndarray:
    """Same order defect represented as an operator on channel generators."""
    return order_defect(ad(bg_x), ad(bg_y))


def extract_extra_unit(
    h_self: np.ndarray, bg_x: np.ndarray, bg_y: np.ndarray
) -> tuple[float, float]:
    """Fit H_xy=-c K0_op. c is predicted to be one, with no free scale."""
    k_op = curvature_operator(bg_x, bg_y)
    denom = float(np.sum(k_op * k_op))
    if denom < 1e-20:
        raise ValueError("zero order defect; self-interaction unit undefined")
    off = h_self[:3, 3:]
    coefficient = -float(np.sum(off * k_op)) / denom
    residual = np.linalg.norm(off + coefficient * k_op) / np.linalg.norm(k_op)
    return coefficient, float(residual)


def background(seed: int = 20) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    bg_x = rng.normal(size=3)
    bg_y = rng.normal(size=3)
    if np.linalg.norm(order_defect(ad(bg_x), ad(bg_y))) < 0.2:
        bg_y += np.array([0.3, -0.4, 0.5])
    return bg_x, bg_y


def test_no_op_identity_fixes_composition_normalization():
    """A rescaled product is forbidden unless it preserves the no-op identity."""
    rng = np.random.default_rng(3)
    x = rng.normal(size=(3, 3))
    identity = np.eye(3)
    assert np.linalg.norm(compose(identity, x) - x) < TOL
    assert np.linalg.norm(compose(x, identity) - x) < TOL
    scale = 1.7
    assert np.linalg.norm(scale * compose(identity, x) - x) > 1e-3


def test_order_defect_is_exchange_odd_and_jacobi_follows_from_composition():
    """The circulation operation is generated from composition and is coherent."""
    rng = np.random.default_rng(7)
    x, y, z = (rng.normal(size=(3, 3)) for _ in range(3))
    assert np.linalg.norm(order_defect(x, y) + order_defect(y, x)) < TOL
    jacobi = (
        order_defect(x, order_defect(y, z))
        + order_defect(y, order_defect(z, x))
        + order_defect(z, order_defect(x, y))
    )
    assert np.linalg.norm(jacobi) < TOL


def test_bilinearity_forces_the_quadratic_self_term_with_unit_coefficient():
    """No [a,a] input: it appears as the epsilon^2 coefficient of one K."""
    rng = np.random.default_rng(11)
    bg_x, bg_y = background()
    a_x, a_y = rng.normal(size=3), rng.normal(size=3)
    k0, k1, k2 = curvature_coefficients(bg_x, bg_y, a_x, a_y)
    for eps in (-0.7, -0.2, 0.3, 0.9):
        predicted = k0 + eps * k1 + eps**2 * k2
        measured = full_curvature(eps, bg_x, bg_y, a_x, a_y)
        assert np.linalg.norm(measured - predicted) < TOL
    h = 0.25
    second = (
        full_curvature(h, bg_x, bg_y, a_x, a_y)
        - 2 * full_curvature(0.0, bg_x, bg_y, a_x, a_y)
        + full_curvature(-h, bg_x, bg_y, a_x, a_y)
    ) / h**2
    assert np.linalg.norm(second - 2.0 * k2) < TOL


def test_forced_self_term_supplies_exactly_one_curvature_unit():
    bg_x, bg_y = background()
    h_self = self_interaction_hessian(bg_x, bg_y)
    coefficient, residual = extract_extra_unit(h_self, bg_x, bg_y)
    assert abs(coefficient - 1.0) < TOL, coefficient
    assert residual < TOL, residual
    assert np.linalg.norm(h_self[:3, :3]) < TOL
    assert np.linalg.norm(h_self[3:, 3:]) < TOL


def test_commutative_and_external_payload_controls_kill_the_extra_unit():
    """The unit requires both noncommutativity and self-carrier closure."""
    x = np.diag([1.0, 2.0, -1.0])
    y = np.diag([3.0, -4.0, 0.5])
    assert np.linalg.norm(order_defect(x, y)) < TOL

    bg_x, bg_y = background()
    rng = np.random.default_rng(19)
    a_x, a_y = rng.normal(size=3), rng.normal(size=3)
    k0 = channel_bracket(bg_x, bg_y)
    k1 = channel_bracket(bg_x, a_y) + channel_bracket(a_x, bg_y)

    def external_payload_curvature(eps: float) -> np.ndarray:
        return k0 + eps * k1

    h = 0.25
    second = (
        external_payload_curvature(h)
        - 2 * external_payload_curvature(0.0)
        + external_payload_curvature(-h)
    ) / h**2
    assert np.linalg.norm(second) < TOL


def test_gate_bookkeeping_geometry_one_plus_composition_one_gives_four():
    """Downstream identity only; Paper IV independently supplies geo_unit=1."""
    bg_x, bg_y = background()
    comp_unit, residual = extract_extra_unit(
        self_interaction_hessian(bg_x, bg_y), bg_x, bg_y
    )
    geo_unit = 1.0  # executed Paper-IV input, not re-derived in this file
    total_coupling = geo_unit + comp_unit
    assert residual < TOL
    assert abs(total_coupling - 2.0) < TOL
    assert abs(total_coupling**2 - 4.0) < TOL
